// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniBot.Infraestructura.Persistencia;

#nullable disable

namespace MiniBot.Infraestructura.Migrations
{
    [DbContext(typeof(ChatBotDbContext))]
    [Migration("20240704213812_MigracionInical")]
    partial class MigracionInical
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniBot.Dominio.Entitdades.Chat.Diccionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consulta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diccionario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7448ee4-d4aa-462e-b850-1b936f6df765"),
                            Consulta = "",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(426),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Hola! Soy Boti tu asistente virtual, como puedo ayudarte?"
                        },
                        new
                        {
                            Id = new Guid("4281108c-1071-4892-b421-213511b83a5a"),
                            Consulta = "¿Cuáles son los horarios de apertura?",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(446),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Estamos abiertos de lunes a sábado de 8:00 AM a 8:00 PM y los domingos de 9:00 AM a 6:00 PM."
                        },
                        new
                        {
                            Id = new Guid("01c04ace-8340-46d7-9428-5e94030b1ca4"),
                            Consulta = "¿Dónde están ubicados?",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(448),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Estamos ubicados en la calle Principal, número 123, en el centro de la ciudad"
                        },
                        new
                        {
                            Id = new Guid("8db4f9d5-ce82-4dce-9611-aafcbc53d0d4"),
                            Consulta = "¿Ofrecen servicio de entrega a domicilio?",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(465),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, ofrecemos servicio de entrega a domicilio. Puedes realizar tu pedido en línea o llamarnos al (123) 456-7890."
                        },
                        new
                        {
                            Id = new Guid("0e11f092-c91a-46c1-8434-51abbcd376a1"),
                            Consulta = "¿Aceptan tarjetas de crédito?",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(468),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, aceptamos todas las tarjetas de crédito y débito principales."
                        },
                        new
                        {
                            Id = new Guid("e4726597-1b36-4461-bab5-19a05b10471e"),
                            Consulta = "¿Tienen productos orgánicos?",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(474),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, contamos con una variedad de productos orgánicos en nuestra tienda."
                        },
                        new
                        {
                            Id = new Guid("47a08b47-fe2a-48e2-95a3-026ae74bd4c1"),
                            Consulta = "¿Cuáles son las promociones actuales?",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(476),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Actualmente, tenemos una promoción de 2x1 en productos seleccionados. Puedes ver todas nuestras ofertas en nuestra página de promociones."
                        },
                        new
                        {
                            Id = new Guid("55f26ffc-7363-4e9c-890b-cea43bc8cabf"),
                            Consulta = " ¿Puedo hacer un pedido especial?",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(478),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, aceptamos pedidos especiales. Por favor, llámanos al (123) 456-7890 para más detalles."
                        },
                        new
                        {
                            Id = new Guid("7ec82c6c-5aa4-427b-89e7-5d1fed3507e5"),
                            Consulta = "¿Tienen productos sin gluten?",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(480),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, tenemos una sección dedicada a productos sin gluten. Puedes pedir más información a nuestro personal en la tienda."
                        },
                        new
                        {
                            Id = new Guid("7739767b-170b-4320-ab16-8c38330390a1"),
                            Consulta = "¿Puedo devolver un producto?",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(483),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, aceptamos devoluciones dentro de los 30 días de la compra con el recibo original."
                        },
                        new
                        {
                            Id = new Guid("deaeb7f8-dc05-4430-b36b-55d61ac6e5e1"),
                            Consulta = "¿Tienen un programa de fidelización?",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(484),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, tenemos un programa de fidelización. Puedes registrarte en nuestra tienda y empezar a acumular puntos con cada compra."
                        },
                        new
                        {
                            Id = new Guid("dfc2d931-e678-4757-85f0-368dfc422906"),
                            Consulta = "",
                            FechaCreacion = new DateTime(2024, 7, 4, 15, 38, 12, 187, DateTimeKind.Local).AddTicks(490),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Lo siento, no tengo contexto para responder tu pregunta, podrias darme mas detalles para ayudarte."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
