// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniBot.Infraestructura.Persistencia;

#nullable disable

namespace MiniBot.Infraestructura.Migrations
{
    [DbContext(typeof(ChatBotDbContext))]
    [Migration("20240705060707_MigracionInical")]
    partial class MigracionInical
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniBot.Dominio.Entitdades.Chat.Diccionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consulta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diccionario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2944e6f-7284-42e6-94b3-e4ceb2ed1d11"),
                            Consulta = "Saludo",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9173),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Hola! Soy Boti tu asistente virtual, como puedo ayudarte?"
                        },
                        new
                        {
                            Id = new Guid("71230187-5936-444f-9bf5-8f33e7117983"),
                            Consulta = "¿Cuáles son los horarios de apertura?",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9195),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Estamos abiertos de lunes a sábado de 8:00 AM a 8:00 PM y los domingos de 9:00 AM a 6:00 PM."
                        },
                        new
                        {
                            Id = new Guid("b3843922-f63e-4666-abd7-14cfaeebb41e"),
                            Consulta = "¿Dónde están ubicados?",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9197),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Estamos ubicados en la calle Principal, número 123, en el centro de la ciudad"
                        },
                        new
                        {
                            Id = new Guid("9ef80278-ffb9-4878-a612-a35be8d1d1d6"),
                            Consulta = "¿Ofrecen servicio de entrega a domicilio?",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9200),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, ofrecemos servicio de entrega a domicilio. Puedes realizar tu pedido en línea o llamarnos al (123) 456-7890."
                        },
                        new
                        {
                            Id = new Guid("d6f035df-3d20-409d-9488-7acbfb05a11f"),
                            Consulta = "¿Aceptan tarjetas de crédito?",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9203),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, aceptamos todas las tarjetas de crédito y débito principales."
                        },
                        new
                        {
                            Id = new Guid("afbdd69f-f3ee-42bc-bda4-4f64c4af0077"),
                            Consulta = "¿Tienen productos orgánicos?",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9208),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, contamos con una variedad de productos orgánicos en nuestra tienda."
                        },
                        new
                        {
                            Id = new Guid("8d867bcf-ce03-4de8-bef9-53da3bc3afc3"),
                            Consulta = "¿Cuáles son las promociones actuales?",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9211),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Actualmente, tenemos una promoción de 2x1 en productos seleccionados. Puedes ver todas nuestras ofertas en nuestra página de promociones."
                        },
                        new
                        {
                            Id = new Guid("81c560eb-7647-4bf7-9cdc-5791530bd65b"),
                            Consulta = " ¿Puedo hacer un pedido especial?",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9228),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, aceptamos pedidos especiales. Por favor, llámanos al (123) 456-7890 para más detalles."
                        },
                        new
                        {
                            Id = new Guid("3940e524-a04c-434b-924d-78e6464b7309"),
                            Consulta = "¿Tienen productos sin gluten?",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9231),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, tenemos una sección dedicada a productos sin gluten. Puedes pedir más información a nuestro personal en la tienda."
                        },
                        new
                        {
                            Id = new Guid("a41c12c3-4f77-4bb2-bbe9-931df9f4a419"),
                            Consulta = "¿Puedo devolver un producto?",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9234),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, aceptamos devoluciones dentro de los 30 días de la compra con el recibo original."
                        },
                        new
                        {
                            Id = new Guid("d33c1fd3-6563-43d8-9d10-c22926a835d4"),
                            Consulta = "¿Tienen un programa de fidelización?",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9237),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Sí, tenemos un programa de fidelización. Puedes registrarte en nuestra tienda y empezar a acumular puntos con cada compra."
                        },
                        new
                        {
                            Id = new Guid("7366a0c4-3a8d-4c54-867d-0a847e4c783a"),
                            Consulta = "No reconocida",
                            FechaCreacion = new DateTime(2024, 7, 5, 0, 7, 5, 200, DateTimeKind.Local).AddTicks(9239),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Respuesta = "Lo siento, no tengo contexto para responder tu pregunta, podrias darme mas detalles para ayudarte."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
